// Auto-generated by: pnpm supabase gen types typescript --local > src/types/database.types.ts
// Do not edit manually

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string | null;
          avatar_url: string | null;
          birth_date: string | null;
          document: string | null;
          gender: "male" | "female" | "other" | "prefer_not_to_say" | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      establishments: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          category: string;
          logo_url: string | null;
          cover_url: string | null;
          primary_color: string;
          email: string | null;
          phone: string | null;
          whatsapp: string | null;
          instagram: string | null;
          website: string | null;
          address_zip: string | null;
          address_street: string | null;
          address_number: string | null;
          address_complement: string | null;
          address_neighborhood: string | null;
          address_city: string | null;
          address_state: string | null;
          address_country: string;
          latitude: number | null;
          longitude: number | null;
          booking_advance_min_hours: number;
          booking_advance_max_days: number;
          cancellation_hours_before: number;
          require_deposit: boolean;
          deposit_percentage: number;
          auto_confirm: boolean;
          buffer_minutes: number;
          owner_id: string;
          plan: string;
          plan_status: string;
          trial_ends_at: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["establishments"]["Row"],
          "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["establishments"]["Insert"]>;
      };
      establishment_members: {
        Row: {
          id: string;
          establishment_id: string;
          user_id: string;
          role: "owner" | "professional" | "staff";
          display_name: string;
          bio: string | null;
          specialties: string[] | null;
          commission_percentage: number;
          is_active: boolean;
          is_visible_public: boolean;
          position: number;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["establishment_members"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["establishment_members"]["Insert"]>;
      };
      services: {
        Row: {
          id: string;
          establishment_id: string;
          name: string;
          description: string | null;
          category: string | null;
          duration_minutes: number;
          price_cents: number;
          image_url: string | null;
          is_active: boolean;
          requires_consultation: boolean;
          position: number;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["services"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["services"]["Insert"]>;
      };
      professional_services: {
        Row: {
          professional_id: string;
          service_id: string;
          custom_price_cents: number | null;
          custom_duration_minutes: number | null;
        };
        Insert: Database["public"]["Tables"]["professional_services"]["Row"];
        Update: Partial<Database["public"]["Tables"]["professional_services"]["Insert"]>;
      };
      availability_rules: {
        Row: {
          id: string;
          professional_id: string;
          weekday: number;
          start_time: string;
          end_time: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["availability_rules"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["availability_rules"]["Insert"]>;
      };
      time_off: {
        Row: {
          id: string;
          professional_id: string;
          starts_at: string;
          ends_at: string;
          reason: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["time_off"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["time_off"]["Insert"]>;
      };
      appointments: {
        Row: {
          id: string;
          establishment_id: string;
          professional_id: string;
          service_id: string;
          client_id: string | null;
          client_name: string;
          client_email: string;
          client_phone: string;
          client_notes: string | null;
          starts_at: string;
          ends_at: string;
          service_name_snapshot: string;
          price_cents_snapshot: number;
          duration_minutes_snapshot: number;
          status: "pending" | "confirmed" | "cancelled" | "no_show" | "completed" | "rescheduled";
          cancellation_reason: string | null;
          cancelled_by: string | null;
          payment_status: "not_required" | "pending" | "paid" | "refunded" | "failed";
          deposit_cents: number;
          payment_provider: string | null;
          payment_intent_id: string | null;
          source: string;
          reminded_24h: boolean;
          reminded_2h: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["appointments"]["Row"],
          "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["appointments"]["Insert"]>;
      };
      reviews: {
        Row: {
          id: string;
          appointment_id: string;
          establishment_id: string;
          professional_id: string;
          client_id: string | null;
          rating: number;
          comment: string | null;
          is_public: boolean;
          owner_response: string | null;
          owner_responded_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["reviews"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["reviews"]["Insert"]>;
      };
      portfolio_items: {
        Row: {
          id: string;
          establishment_id: string;
          professional_id: string | null;
          image_url: string;
          thumbnail_url: string | null;
          title: string | null;
          description: string | null;
          tags: string[] | null;
          is_featured: boolean;
          position: number;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["portfolio_items"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["portfolio_items"]["Insert"]>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          establishment_id: string | null;
          type: string;
          title: string;
          body: string;
          data: Json | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["notifications"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["notifications"]["Insert"]>;
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh_key: string;
          auth_key: string;
          user_agent: string | null;
          created_at: string;
          last_used_at: string | null;
        };
        Insert: Omit<Database["public"]["Tables"]["push_subscriptions"]["Row"], "created_at">;
        Update: Partial<Database["public"]["Tables"]["push_subscriptions"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      user_establishments: {
        Args: { user_uuid: string };
        Returns: string[];
      };
    };
    Enums: Record<string, never>;
  };
}

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
